<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Aryans-MacBook-Pro.local" failures="2" tests="2" name="com.aryan.SignupServletTest" time="0.082" errors="0" timestamp="2024-12-31T01:55:53 IST" skipped="0">
  <testcase classname="com.aryan.SignupServletTest" name="testValidSignup" time="0.025">
    <failure message="Argument(s) are different! Wanted:
httpServletResponse.sendRedirect(
    &quot;/login.jsp&quot;
);
-&gt; at com.aryan.SignupServletTest.testValidSignup(SignupServletTest.java:35)
Actual invocations have different arguments:
httpServletResponse.sendRedirect(
    &quot;null/login.jsp&quot;
);
-&gt; at com.aryan.SignupServlet.doPost(SignupServlet.java:32)
" type="org.mockito.exceptions.verification.ArgumentsAreDifferent">
      <![CDATA[org.mockito.exceptions.verification.ArgumentsAreDifferent: Argument(s) are different! Wanted:
httpServletResponse.sendRedirect(
    "/login.jsp"
);
-> at com.aryan.SignupServletTest.testValidSignup(SignupServletTest.java:35)
Actual invocations have different arguments:
httpServletResponse.sendRedirect(
    "null/login.jsp"
);
-> at com.aryan.SignupServlet.doPost(SignupServlet.java:32)

at com.aryan.SignupServletTest.testValidSignup(SignupServletTest.java:35)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:324)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:74)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:123)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
]]>
    </failure>
  </testcase> <!-- testValidSignup -->
  <testcase classname="com.aryan.SignupServletTest" name="testDuplicateUserSignup" time="0.057">
    <failure message="
Wanted but not invoked:
httpServletRequest.setAttribute(
    &quot;errorMessage&quot;,
    &quot;Username or email already exists.&quot;
);
-&gt; at com.aryan.SignupServletTest.testDuplicateUserSignup(SignupServletTest.java:55)

However, there were exactly 4 interactions with this mock:
httpServletRequest.getParameter(&quot;username&quot;);
-&gt; at com.aryan.SignupServlet.doPost(SignupServlet.java:18)

httpServletRequest.getParameter(&quot;email&quot;);
-&gt; at com.aryan.SignupServlet.doPost(SignupServlet.java:19)

httpServletRequest.getParameter(&quot;password&quot;);
-&gt; at com.aryan.SignupServlet.doPost(SignupServlet.java:20)

httpServletRequest.getContextPath();
-&gt; at com.aryan.SignupServlet.doPost(SignupServlet.java:32)

" type="org.mockito.exceptions.verification.WantedButNotInvoked">
      <![CDATA[Wanted but not invoked:
httpServletRequest.setAttribute(
    "errorMessage",
    "Username or email already exists."
);
-> at com.aryan.SignupServletTest.testDuplicateUserSignup(SignupServletTest.java:55)

However, there were exactly 4 interactions with this mock:
httpServletRequest.getParameter("username");
-> at com.aryan.SignupServlet.doPost(SignupServlet.java:18)

httpServletRequest.getParameter("email");
-> at com.aryan.SignupServlet.doPost(SignupServlet.java:19)

httpServletRequest.getParameter("password");
-> at com.aryan.SignupServlet.doPost(SignupServlet.java:20)

httpServletRequest.getContextPath();
-> at com.aryan.SignupServlet.doPost(SignupServlet.java:32)


at com.aryan.SignupServletTest.testDuplicateUserSignup(SignupServletTest.java:55)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:324)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:74)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:123)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
]]>
    </failure>
  </testcase> <!-- testDuplicateUserSignup -->
</testsuite> <!-- com.aryan.SignupServletTest -->
